version: "3"

services:
  pg:
    image: pgtesting:prod
    container_name: pgprod
    ports:
      - 8090:8090
      - 8050:8050
#      - 8888:8888
    environment:
      - TZ=Europe/Helsinki
  pgtest:
    image: pgtesting:testing
    container_name: pgtesting
    ports:
      - 8060:8050
#      - 8888:8888
    environment:
      - TZ=Europe/Helsinki

#    volumes:
#      - /srv/mergerfs/Grand/Shared/Dockertesting:/test
