version: "3"

services:
  pg:
    image: pgtesting:current
    container_name: pg
    ports:
      - 8090:8090
      - 8050:8050
#      - 8888:8888
    environment:
      - TZ=Europe/Helsinki

#    volumes:
#      - /srv/mergerfs/Grand/Shared/Dockertesting:/test
