version: "3"

services:
  pgyver_testing:
    image: pgtesting:v1.102
    container_name: pgyver_v1.102
    ports:
      - 8060:8050
    environment:
      - TZ=Europe/Helsinki

    volumes:
      - /mnt/varjosalo_MS_rundata:/proteogyver/data/MS_rundata
      - /mnt/varjosalo_Server_output:/proteogyver/data/Server_output
