version: "3"

services:
  proteogyver:
    image: pgtesting:latest
    ports:
      - 8090:8090
      - 8050:8050
#      - 8888:8888
    volumes:
      - /srv/mergerfs/Grand/Shared/Dockertesting:/test
