version: "3"

services:
  pgyver_testing:
    image: pgyver:v1.2t
    container_name: pgyver1.2t
    ports:
      - 8060:8050
    environment:
      - TZ=Europe/Helsinki

    volumes:
      - /mnt/varjosalo_MS_rundata:/proteogyver/data/MS_rundata
      - /mnt/varjosalo_Server_output:/proteogyver/data/Server_output
