[general]
# Workflow type: "proteomics" or "interactomics"
workflow = "proteomics"

# Input data files (paths relative to this TOML file)
data = "datafiles/Proteomics data file.tsv"
sample table = "datafiles/Proteomics sample table.tsv"

[proteomics]
# NA filtering
na_filter_percent = 70 # 0-100
na_filter_type = "sample-set"  # "sample-group" or "sample-set"

# Normalization method
normalization = "Median"  # "Median", "Quantile", "Vsn", or "no_normalization"
