services:
  pg_update:
    image: pgu:1.3d
    container_name: pgu13d
    environment:
      TZ: Europe/Helsinki
      FORCE_PG_DB_UPDATE: '0' # set to '1' to force a full database update, otherwise only updates that are due will be performed.
    volumes:
      - /data/PG/cache:/proteogyver/cache
      - /data/PG/db:/proteogyver/data/db
      - /data/PG/input:/proteogyver/data/Server_input
      - /data/PG/output:/proteogyver/data/Server_output
      # This is required for the updater to share one parameter file with the server.
      - /data/PG/config:/proteogyver/config
      - /data/PG/api_data:/proteogyver/components/api_tools/data
    restart: no
