services:
  pg_database_updater:
    image: pg_updater:1.5
    container_name: pgu15
    environment:
      TZ: Europe/Helsinki
      FORCE_PG_DB_UPDATE: '0' # set to '1' to force a full database update, otherwise only updates that are due will be performed.
    volumes:
      - /data/PG15/cache:/proteogyver/cache
      - /data/PG15/db:/proteogyver/data/db
      - /data/PG15/input:/proteogyver/data/Server_input
      - /data/PG15/output:/proteogyver/data/Server_output
      # This is required for the updater to share one parameter file with the server.
      - /data/PG15/config:/proteogyver/config
      - /data/PG15/api_data:/proteogyver/components/api_tools/data
    restart: no
