services:
  pg_update:
    image: pg_updater:1.2
    container_name: pg_updater
    environment:
      TZ: Europe/Helsinki
    volumes:
      - /data/PG_containers/cache/PG_rev:/proteogyver/cache
      - /data/PG_containers/db/PG_rev:/proteogyver/data/db
      - /data/PG_containers/input:/proteogyver/data/Server_input
      - /data/PG_containers/output:/proteogyver/data/Server_output
      - /data/PG_containers/api_data:/proteogyver/components/api_tools/data
      # This is required for the updater to share one parameter file with the server.
      - /data/PG_containers/conf/PG_rev/parameters.toml:/proteogyver/parameters.toml
