name: PG
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - amqp=5.2.0=pyhd8ed1ab_2
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - billiard=4.2.2=py312h4c3975b_1
  - biopython=1.85=py312h4c3975b_2
  - blas=2.137=openblas
  - blas-devel=3.9.0=37_h1ea3ea9_openblas
  - blinker=1.9.0=pyhff2d567_0
  - boto3=1.40.55=pyhd8ed1ab_0
  - botocore=1.40.55=pyhd8ed1ab_0
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.1.0=py312h1289d80_4
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - celery=5.5.3=pyhe01879c_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py312h35888ee_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - click-didyoumean=0.3.1=pyhd8ed1ab_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - click-repl=0.3.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - colour=0.1.5=pyhd8ed1ab_2
  - contourpy=1.3.3=py312hd9148b4_2
  - coverage=7.11.0=py312h8a5da7c_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dash=3.2.0=pyhd8ed1ab_0
  - dash-bio=1.0.2=pyhd8ed1ab_0
  - dash-bootstrap-components=2.0.4=pyhcf101f3_0
  - dash-core-components=2.0.0=pyhd8ed1ab_1
  - dash-html-components=2.0.0=pyhd8ed1ab_2
  - dash-table=5.0.0=pyhd8ed1ab_1
  - dash_cytoscape=0.2.0=pyhd8ed1ab_1
  - dateutils=0.6.12=pyhd8ed1ab_1
  - dbus=1.16.2=h3c4dab8_0
  - double-conversion=3.3.1=h5888daf_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - flask=3.1.2=pyhd8ed1ab_0
  - flask-compress=1.18=pyhe01879c_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py312h8a5da7c_0
  - freetype=2.14.1=ha770c72_0
  - geoparse=2.0.4=pyhd8ed1ab_1
  - graphite2=1.3.14=hecca717_2
  - gunicorn=23.0.0=py312h7900ff3_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.1.0=h15599e2_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py312h0a2e395_1
  - kombu=5.5.4=pyha770c72_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcblas=3.9.0=37_h0358290_openblas
  - libclang-cpp21.1=21.1.3=default_h99862b1_0
  - libclang13=21.1.3=default_h746c552_0
  - libcups=2.3.3=hb8b1518_5
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.0=h1fed272_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=37_h47877c9_openblas
  - liblapacke=3.9.0=37_h6ae95b6_openblas
  - libllvm21=21.1.3=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=18.0=h3675c94_0
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.7.1=h8261f1e_0
  - libuuid=2.41.2=he9a06e4_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.12.1=hca5e8e5_0
  - libxml2=2.15.0=h26afc86_1
  - libxml2-16=2.15.0=ha9997c6_1
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.45.1=py312h7424e68_0
  - markupsafe=3.0.3=py312h8a5da7c_0
  - matplotlib=3.10.7=py312h7900ff3_0
  - matplotlib-base=3.10.7=py312he3d6523_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.8.0=pyhcf101f3_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numba=0.62.1=py312h907b442_0
  - numpy=2.3.3=py312h33ff503_0
  - openblas=0.3.30=pthreads_h6ec200e_2
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openpyxl=3.1.5=py312h7f6eeab_2
  - openssl=3.5.4=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hf79963d_1
  - parmed=4.3.0=py312ha9124a0_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.46=h1321c63_0
  - periodictable=1.7.1=pyhd8ed1ab_0
  - pillow=11.3.0=py312h7b42cdd_3
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - plotly=6.3.1=pyhd8ed1ab_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.9.3=py312h9da60e5_1
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=8.4.2=pyhd8ed1ab_0
  - pytest-cov=7.0.0=pyhcf101f3_1
  - python=3.12.12=hfe2f287_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzstd=0.18.0=py312h3fa7853_0
  - qhull=2020.2=h434a139_5
  - qnorm=0.9.0=pyhff2d567_0
  - qt6-main=6.9.3=h5c1c036_0
  - readlif=0.6.6=pyhc364b38_0
  - readline=8.2=h8c095d6_2
  - redis-py=6.4.0=pyhd8ed1ab_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - retrying=1.4.2=pyhe01879c_0
  - rpds-py=0.27.1=py312h868fb18_1
  - s3transfer=0.14.0=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py312h4f0b9e3_0
  - scipy=1.16.2=py312h7a1785b_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - statsmodels=0.14.5=py312h4f23490_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_hd72426e_102
  - tomli=2.3.0=pyhcf101f3_0
  - tomlkit=0.13.3=pyha770c72_0
  - tornado=6.5.2=py312h4c3975b_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py312h4c3975b_1
  - unidecode=1.3.8=pyh29332c3_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vine=5.1.0=pyhd8ed1ab_1
  - wayland=1.24.0=h3e06ad9_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xlrd=2.0.2=pyhd8ed1ab_0
  - xmltodict=1.0.2=pyhcf101f3_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.25.0=py312h5253ce2_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
    - alphatims==1.0.8
    - celery_once==3.0.1
    - dash_uploader==0.6.1
    - h5py==3.15.1
    - kaleido==0.2.1
    - nbib==0.3.2
    - psutil==7.1.1
    - supervenn==0.5.0

prefix: "/home/kmsaloka/.micromamba/envs/PG"
